// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtbudefmoynstdknugzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0YnVkZWZtb3luc3Rka251Z3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDYwNDksImV4cCI6MjA2NTM4MjA0OX0.r1PKpP3Ae1y7IzgQVHvYhTnY0mOmBWmflYCfjeT2BOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);